# run with treefmt --allow-missing-formatter

[global]
excludes = [
  # txt files
  "**/*.txt",
  # gitignore
  "**/.gitignore",
  # go.sum & go.mod
  "go.sum",
  "go.mod",
  # testdata
  "testdata/**",
]

### Go

[formatter.gofumpt]
command = "gofumpt"
options = ["-w"]
includes = ["*.go"]

[formatter.gci]
command = "gci"
options = ["-w"]
includes = ["*.go"]
priority = 1        # run after gofumpt
